### ISSUE TITLE
TODO: predictInterval()

### ISSUE THREAD

**Issue by carlbfrederick** [jknowles/merTools#1]
* [x] develop summary measures to evaluate our prediction versus other `bootMer()` and `predict.merMod()` methods
  + [x] % overlap of PI
  + [x] some sort of bias analog: `abs(kf.method)` versus `abs(other.method)`
  + [x] other graphical methods ?

*  [x] Let function handle groups in `newdata` that are not in original model frame gracefully ... e.g. draw BLUP from `\theta` and issue a warning listing groups that are unique to `newdata`

* [x] Check my algebra/calculations of the linear predictors

* [x] Allow user to choose:
   + [x] to predict either linear predictor or response categories
   + [x] mean or median of yhat samples
   + [x] number of simulations

**Comment by carlbfrederick** [comment]
I am currently trying to work out the case where newdata has levels that are not in the model.  The mechanics work, but I am trying to figure out exactly what those predictions are.  Essentially they are straight from `simBeta` and a warning is issued to alert the user.

My questions is: are we using the individual level variation in the predictions at all and, if not, if we should be worried about this?

I have pushed this change up to GitHub in merPredict.R
